version: '3.4'

x-django_env: &DJANGO_ENV
  DJANGO_SETTINGS_MODULE: config.settings.dev

services:
  redditanalysis:
    image: redditanalysis
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .docker_bash_aliases:/root/.bash_aliases
      - .:/app:cached
    ports:
      - 8000:8000
      - 5678:5678
    tty: true
    env_file: .env
    environment:
      TERM: xterm-color
      <<: *DJANGO_ENV
