version: '3.4'

x-django_env: &DJANGO_ENV
  DJANGO_SETTINGS_MODULE: config.settings.dev

services:
  
  web:
    container_name: web

    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .docker_bash_aliases:/root/.bash_aliases
      - .:/code:cached

    ports:
      - "8000:8000"

    tty: true
    environment:
      TERM: xterm-color
      <<: *DJANGO_ENV

  node:
    container_name: node
    image: node
    build:
      context: .
      dockerfile: Dockerfile.node
    working_dir: /code

    command: sh -c "npm run watch"

    volumes:
      - .:/code
      - node-data:/code/node_modules

    ports:
      - 35729:35729

    environment:
      NODE_ENV: development
volumes:
  node-data:
